name: 生成配置文件

on:
  # repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH Action'
        required: false
        default: 'false'

env: 
  FEEDS_CONF: config/feeds.conf.default
  CONFIG_FILE: config/.config
  cCONF: 
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: false
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 检查
      uses: actions/checkout@main

    - name: 创建环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential bc clang flex g++ gawk gcc-multilib gettext \
        git libncurses5-dev libssl-dev python3-distutils python3-pyelftools libpython3-dev rsync unzip zlib1g-dev swig aria2 jq subversion qemu-utils ccache rename libelf-dev device-tree-compiler libgnutls28-dev
        sudo -E apt-get -qq purge azure-cli ghc* zulu* llvm* firefox powershell openjdk* dotnet* google* mysql* php* android*
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /lede
        sudo chown $USER:$GROUPS /lede

    - name: 下载Lede源码
      working-directory: /lede
      run: |
        df -hT $PWD
        git clone https://github.com/coolsnowwolf/lede.git openwrt
        ln -sf /lede/openwrt $GITHUB_WORKSPACE/openwrt

    - name: 覆写插件
      run: |
        [ -e $FEEDS_CONF ] && cp -f $FEEDS_CONF /lede/openwrt/feeds.conf.default
        cd /lede/openwrt
        make defconfig

    - name: 更新插件库
      run: | 
        cd /lede/openwrt && ./scripts/feeds update -a

    - name: 安装插件库
      run: | 
        cd /lede/openwrt && ./scripts/feeds install -a

    - name: 删除冲突插件
      run: | 
        rm -rf feeds/smpackage/{base-files,dnsmasq,firewall*,fullconenat,libnftnl,nftables,ppp,opkg,ucl,upx,vsftpd-alt,miniupnpd-iptables,wireless-regdb}
        
    - name: 覆写配置
      run: |
        [ -e $CONFIG_FILE ] && cp -f $CONFIG_FILE /lede/openwrt/.config
        cd /lede/openwrt
        sed -i 's/192.168.1.1/192.168.3.10/g' package/base-files/files/bin/config_generate
        sed -i 's/OpenWrt/Jayha/g' package/base-files/files/bin/config_generate

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        # TELEGRAM_CHAT_ID: ${{ secrets.API_ID }}
        # TELEGRAM_BOT_TOKEN: ${{ secrets.API_HASH }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

    - name: 打包文件
      run: |
        sudo zip -rj config.zip /lede/openwrt/.config
        mkdir -p ./bin/conf
        sudo chmod 777 ./bin/conf
        sudo mv -f config.zip ./bin/conf/conf_&(date +%Y-%m-%d-%H-%M-%S)

    - name: 上传config
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt.config
        path: ./bin/conf/*


    - name: Test Post Large File
      uses: xireiki/channel-post@v1
      with:
        bot_token: ${{ secrets.BOT_TOKEN }}
        chat_id: ${{ secrets.CHAT_ID }}
        context: Openwrt Conf
        method: sendFile # sendDocument、sendMediaGroup
        path: ./bin/conf/* # Total size does not exceed 2000M
        large_file: true
        api_id: ${{ secrets.API_ID }} # 12345678
        api_hash: ${{ secrets.API_HASH }} # 01234567890abcdef01234567890abcdef

